# config data bases
#spring:
#profiles: test
#jmx:
#enabled: false
# Datasource and JPA configuration to be used for using the same tokenstore as the authorization server for
# the defined resource server. Note that there can't be 2 different root nodes, so datasource falls under the "spring" node.
#datasource:
#url: jdbc:mysql://192.168.109.34:3306/mrn
#username: root
#password: mysql
#driver-class: com.mysql.jdbc.Driver
#initialize: true
#separator: ^
#continueOnError: false
#schema: classpath:/db-scripts/0.0.1/schema.sql
#data: classpath:/db-scripts/0.0.1/masterData.sql
#
#jpa:
#database-platform: org.hibernate.dialect.MySQLDialect
#show-sql: true
#hibernate:
#ddl-auto: create
#show_sql: true
#naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
# Logging settings.
logging:
  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
  level:
    com.transoft.completeair.mrn: DEBUG

    # Logger-specific levels.
    #!loggers:
    # Redirects SQL logs to a separate file
    #!org.hibernate.SQL: DEBUG, ERROR
    #!org.springframework.web: DEBUG, ERROR

# Note: import disable mode product and active mode Dev
server:
  port: 8086
# config data bases
spring:
  # config Rabbitmq
  cloud:
    stream:
      #bindings:
      binders:
        rabbit1:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: 192.168.7.133
                port: 5672
                username: admin
                password: admin
# Config KieServer
kieServer:
  user: kieserver
  password: kieserver,.!
  url: http://172.16.20.112:8080/kie-server/services/rest/server
  containerId: fare-engine-tam
  fare:
    user: kieserver
    password: kieserver,.!
    url: http://172.16.20.112:8080/kie-server/services/rest/server
    container: fare-engine-tam
  waitingList:
    user: kieserver
    password: kieserver,.!
    url: http://172.16.10.223:8080/kie-server/services/rest/server
    container: waiting-list-tam
#Config Eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.7.186:8761/eureka/
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${server.port}

security:
  oauth2:
    resource:
      userInfoUri: http://192.168.7.186:9999/uaa/api/user
